import {
  abyssalTentacle,
  abyssalWhip,
  achievementDiaryCape,
  adamantStaffOfCollection,
  agilityCape,
  ahrimsHood,
  anglerHat,
  arcanePrayerScroll,
  attackCape,
  barrowsGloves,
  basiliskJaw,
  blackStaffOfCollection,
  bronzeStaffOfCollection,
  championsCape,
  clueScrollBeginner,
  clueScrollEasy,
  clueScrollElite,
  clueScrollHard,
  clueScrollMaster,
  clueScrollMedium,
  constructCape,
  cookingCape,
  craftingCape,
  crystalArmourSeed,
  defenceCape,
  dexterousPrayerScroll,
  dharoksHelm,
  dragonHunterLance,
  dragonStaffOfCollection,
  enhancedCrystalWeaponSeed,
  farmingCape,
  fireCape,
  firemakingCape,
  fishingCape,
  fletchingCape,
  gildedStaffOfCollection,
  guthansHelm,
  herbloreCape,
  hitpointsCape,
  hunterCape,
  hydrasClaw,
  infernalCape,
  ironStaffOfCollection,
  jarOfDirt,
  karilsCoif,
  krakenTentacle,
  magicCape,
  magicFang,
  maxCape,
  mimic,
  miningCape,
  mithrilStaffOfCollection,
  neitiznotFaceguard,
  occultNecklace,
  petGeneralGraardor,
  prayerCape,
  prayerPotion4,
  prospectorHelmet,
  pyromancerHood,
  questPointCape,
  rangingCape,
  rogueMask,
  runecraftCape,
  runeStaffOfCollection,
  sailingCape,
  saradominBrew4,
  slayerCape,
  smithingCape,
  steelStaffOfCollection,
  strengthCape,
  superCombatPotion4,
  superRestore4,
  thievingCape,
  toragsHelm,
  tridentOfTheSeas,
  tridentOfTheSwamp,
  veracsHelm,
  woodcuttingCape,
  zamorakianSpear,
} from "../../../node_modules/@dava96/osrs-icons/dist/esm/generated/icons.js";
import diaryIcon from "../../assets/atlas/achievement-diaries.png";
import hunllef from "../../assets/atlas/crystalline-hunllef.png";
import elderVenatorFang from "../../assets/atlas/elder-venator-fang.png";
import necklaceOfRupture from "../../assets/atlas/necklace-of-rupture.png";
import {
  agilityIcon,
  combatAchievementsIcon,
  constructionIcon,
  cookingIcon,
  craftingIcon,
  farmingIcon,
  firemakingIcon,
  fishingIcon,
  fletchingIcon,
  herbloreIcon,
  hunterIcon,
  largeMapIcon,
  magicIcon,
  miningIcon,
  prayerIcon,
  prifddinasIcon,
  questStartIcon,
  runecraftIcon,
  skillsIcon,
  slayerIcon,
  smithingIcon,
  thievingIcon,
  toDataUrl,
  woodcuttingIcon,
} from "../../osrsIcons";
import { atlasClueIcons } from "./atlasClueIcons";
import { atlasEquipmentIcons } from "./atlasEquipmentIcons";
import { atlasRecentIcons } from "./atlasRecentIcons";
import { atlasSkillingIcons } from "./atlasSkillingIcons";

export const atlasIcons = {
  necklaceOfRupture,
  elderVenatorFang,
  ...atlasClueIcons,
  ...atlasEquipmentIcons,
  ...atlasRecentIcons,
  ...atlasSkillingIcons,
  diary: diaryIcon,
  ahrimsHood: toDataUrl(ahrimsHood),
  guthansHelm: toDataUrl(guthansHelm),
  karilsCoif: toDataUrl(karilsCoif),
  toragsHelm: toDataUrl(toragsHelm),
  veracsHelm: toDataUrl(veracsHelm),
  pyromancerHood: toDataUrl(pyromancerHood),
  rogueMask: toDataUrl(rogueMask),
  dexterousPrayerScroll: toDataUrl(dexterousPrayerScroll),
  arcanePrayerScroll: toDataUrl(arcanePrayerScroll),

  ...toDataUrl({
    agility: agilityIcon,
    collection: skillsIcon,
    combat: combatAchievementsIcon,
    construction: constructionIcon,
    cooking: cookingIcon,
    crafting: craftingIcon,
    dramen: largeMapIcon,
    farming: farmingIcon,
    firemaking: firemakingIcon,
    fishing: fishingIcon,
    fletching: fletchingIcon,
    herblore: herbloreIcon,
    hunter: hunterIcon,
    magic: magicIcon,
    map: largeMapIcon,
    mining: miningIcon,
    prayer: prayerIcon,
    prif: prifddinasIcon,
    quest: questStartIcon,
    runecraft: runecraftIcon,
    skills: skillsIcon,
    slayer: slayerIcon,
    smithing: smithingIcon,
    thieving: thievingIcon,
    woodcutting: woodcuttingIcon,
    abyssalTentacle,
    abyssalWhip,
    achievementDiaryCape,
    adamantStaffOfCollection,
    agilityCape,
    anglerHat,
    attackCape,
    barrowsGloves,
    basiliskJaw,
    blackStaffOfCollection,
    bronzeStaffOfCollection,
    championsCape,
    clueScrollBeginner,
    clueScrollEasy,
    clueScrollElite,
    clueScrollHard,
    clueScrollMaster,
    clueScrollMedium,
    constructCape,
    cookingCape,
    craftingCape,
    crystalArmourSeed,
    defenceCape,
    dharoksHelm,
    dragonHunterLance,
    dragonStaffOfCollection,
    enhancedCrystalWeaponSeed,
    farmingCape,
    fireCape,
    firemakingCape,
    fishingCape,
    fletchingCape,
    gildedStaffOfCollection,
    herbloreCape,
    hitpointsCape,
    hunterCape,
    hydrasClaw,
    infernalCape,
    ironStaffOfCollection,
    jarOfDirt,
    krakenTentacle,
    magicCape,
    magicFang,
    maxCape,
    mimic,
    miningCape,
    mithrilStaffOfCollection,
    neitiznotFaceguard,
    occultNecklace,
    petGeneralGraardor,
    prayerCape,
    prayerPotion4,
    prospectorHelmet,
    questPointCape,
    rangingCape,
    runeStaffOfCollection,
    runecraftCape,
    sailingCape,
    saradominBrew4,
    slayerCape,
    smithingCape,
    steelStaffOfCollection,
    strengthCape,
    superCombatPotion4,
    superRestore4,
    thievingCape,
    tridentOfTheSeas,
    tridentOfTheSwamp,
    woodcuttingCape,
    zamorakianSpear,
  }),
  hunllef,
};
