import {
  cluelessScroll,
  heavyCasket,
  largeSpade,
  majorBeginnerScrollCase,
  majorEasyScrollCase,
  majorEliteScrollCase,
  majorHardScrollCase,
  majorMasterScrollCase,
  majorMediumScrollCase,
  mimicScrollCase,
  minorBeginnerScrollCase,
  minorEasyScrollCase,
  minorEliteScrollCase,
  minorHardScrollCase,
  minorMasterScrollCase,
  minorMediumScrollCase,
  scrollSack,
} from "../../../node_modules/@dava96/osrs-icons/dist/esm/generated/icons.js";
import { toDataUrl } from "../../osrsIcons";

export const atlasClueIcons = toDataUrl({
  cluelessScroll,
  heavyCasket,
  largeSpade,
  majorBeginnerScrollCase,
  majorEasyScrollCase,
  majorEliteScrollCase,
  majorHardScrollCase,
  majorMasterScrollCase,
  majorMediumScrollCase,
  mimicScrollCase,
  minorBeginnerScrollCase,
  minorEasyScrollCase,
  minorEliteScrollCase,
  minorHardScrollCase,
  minorMasterScrollCase,
  minorMediumScrollCase,
  scrollSack,
});
