/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgRatingDotpngRouteImport } from './routes/og/rating[.]png'
import { Route as OgRatingRsnRouteImport } from './routes/og/rating/$rsn'
import { Route as CompareLeftRsnRightRsnRouteImport } from './routes/compare/$leftRsn/$rightRsn'
import { Route as CompareLeftRsnRightRsnIndexRouteImport } from './routes/compare/$leftRsn/$rightRsn/index'
import { Route as OgCompareLeftRsnRightRsnRouteImport } from './routes/og/compare/$leftRsn/$rightRsn'
import { Route as CompareLeftRsnRightRsnXpTimelineRouteImport } from './routes/compare/$leftRsn/$rightRsn/xp-timeline'
import { Route as CompareLeftRsnRightRsnSkillsRouteImport } from './routes/compare/$leftRsn/$rightRsn/skills'
import { Route as CompareLeftRsnRightRsnQuestsRouteImport } from './routes/compare/$leftRsn/$rightRsn/quests'
import { Route as CompareLeftRsnRightRsnMinigamesRouteImport } from './routes/compare/$leftRsn/$rightRsn/minigames'
import { Route as CompareLeftRsnRightRsnEfficiencyRouteImport } from './routes/compare/$leftRsn/$rightRsn/efficiency'
import { Route as CompareLeftRsnRightRsnCombatAchievementsRouteImport } from './routes/compare/$leftRsn/$rightRsn/combat-achievements'
import { Route as CompareLeftRsnRightRsnCollectionsRouteImport } from './routes/compare/$leftRsn/$rightRsn/collections'
import { Route as CompareLeftRsnRightRsnCluesRouteImport } from './routes/compare/$leftRsn/$rightRsn/clues'
import { Route as CompareLeftRsnRightRsnBossingRouteImport } from './routes/compare/$leftRsn/$rightRsn/bossing'
import { Route as CompareLeftRsnRightRsnActivityRouteImport } from './routes/compare/$leftRsn/$rightRsn/activity'
import { Route as CompareLeftRsnRightRsnAchievementDiariesRouteImport } from './routes/compare/$leftRsn/$rightRsn/achievement-diaries'

const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRatingDotpngRoute = OgRatingDotpngRouteImport.update({
  id: '/og/rating.png',
  path: '/og/rating.png',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRatingRsnRoute = OgRatingRsnRouteImport.update({
  id: '/og/rating/$rsn',
  path: '/og/rating/$rsn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareLeftRsnRightRsnRoute = CompareLeftRsnRightRsnRouteImport.update({
  id: '/compare/$leftRsn/$rightRsn',
  path: '/compare/$leftRsn/$rightRsn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareLeftRsnRightRsnIndexRoute =
  CompareLeftRsnRightRsnIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const OgCompareLeftRsnRightRsnRoute =
  OgCompareLeftRsnRightRsnRouteImport.update({
    id: '/og/compare/$leftRsn/$rightRsn',
    path: '/og/compare/$leftRsn/$rightRsn',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareLeftRsnRightRsnXpTimelineRoute =
  CompareLeftRsnRightRsnXpTimelineRouteImport.update({
    id: '/xp-timeline',
    path: '/xp-timeline',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnSkillsRoute =
  CompareLeftRsnRightRsnSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnQuestsRoute =
  CompareLeftRsnRightRsnQuestsRouteImport.update({
    id: '/quests',
    path: '/quests',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnMinigamesRoute =
  CompareLeftRsnRightRsnMinigamesRouteImport.update({
    id: '/minigames',
    path: '/minigames',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnEfficiencyRoute =
  CompareLeftRsnRightRsnEfficiencyRouteImport.update({
    id: '/efficiency',
    path: '/efficiency',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnCombatAchievementsRoute =
  CompareLeftRsnRightRsnCombatAchievementsRouteImport.update({
    id: '/combat-achievements',
    path: '/combat-achievements',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnCollectionsRoute =
  CompareLeftRsnRightRsnCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnCluesRoute =
  CompareLeftRsnRightRsnCluesRouteImport.update({
    id: '/clues',
    path: '/clues',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnBossingRoute =
  CompareLeftRsnRightRsnBossingRouteImport.update({
    id: '/bossing',
    path: '/bossing',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnActivityRoute =
  CompareLeftRsnRightRsnActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)
const CompareLeftRsnRightRsnAchievementDiariesRoute =
  CompareLeftRsnRightRsnAchievementDiariesRouteImport.update({
    id: '/achievement-diaries',
    path: '/achievement-diaries',
    getParentRoute: () => CompareLeftRsnRightRsnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rating': typeof RatingRoute
  '/og/rating.png': typeof OgRatingDotpngRoute
  '/compare/$leftRsn/$rightRsn': typeof CompareLeftRsnRightRsnRouteWithChildren
  '/og/rating/$rsn': typeof OgRatingRsnRoute
  '/compare/$leftRsn/$rightRsn/achievement-diaries': typeof CompareLeftRsnRightRsnAchievementDiariesRoute
  '/compare/$leftRsn/$rightRsn/activity': typeof CompareLeftRsnRightRsnActivityRoute
  '/compare/$leftRsn/$rightRsn/bossing': typeof CompareLeftRsnRightRsnBossingRoute
  '/compare/$leftRsn/$rightRsn/clues': typeof CompareLeftRsnRightRsnCluesRoute
  '/compare/$leftRsn/$rightRsn/collections': typeof CompareLeftRsnRightRsnCollectionsRoute
  '/compare/$leftRsn/$rightRsn/combat-achievements': typeof CompareLeftRsnRightRsnCombatAchievementsRoute
  '/compare/$leftRsn/$rightRsn/efficiency': typeof CompareLeftRsnRightRsnEfficiencyRoute
  '/compare/$leftRsn/$rightRsn/minigames': typeof CompareLeftRsnRightRsnMinigamesRoute
  '/compare/$leftRsn/$rightRsn/quests': typeof CompareLeftRsnRightRsnQuestsRoute
  '/compare/$leftRsn/$rightRsn/skills': typeof CompareLeftRsnRightRsnSkillsRoute
  '/compare/$leftRsn/$rightRsn/xp-timeline': typeof CompareLeftRsnRightRsnXpTimelineRoute
  '/og/compare/$leftRsn/$rightRsn': typeof OgCompareLeftRsnRightRsnRoute
  '/compare/$leftRsn/$rightRsn/': typeof CompareLeftRsnRightRsnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rating': typeof RatingRoute
  '/og/rating.png': typeof OgRatingDotpngRoute
  '/og/rating/$rsn': typeof OgRatingRsnRoute
  '/compare/$leftRsn/$rightRsn/achievement-diaries': typeof CompareLeftRsnRightRsnAchievementDiariesRoute
  '/compare/$leftRsn/$rightRsn/activity': typeof CompareLeftRsnRightRsnActivityRoute
  '/compare/$leftRsn/$rightRsn/bossing': typeof CompareLeftRsnRightRsnBossingRoute
  '/compare/$leftRsn/$rightRsn/clues': typeof CompareLeftRsnRightRsnCluesRoute
  '/compare/$leftRsn/$rightRsn/collections': typeof CompareLeftRsnRightRsnCollectionsRoute
  '/compare/$leftRsn/$rightRsn/combat-achievements': typeof CompareLeftRsnRightRsnCombatAchievementsRoute
  '/compare/$leftRsn/$rightRsn/efficiency': typeof CompareLeftRsnRightRsnEfficiencyRoute
  '/compare/$leftRsn/$rightRsn/minigames': typeof CompareLeftRsnRightRsnMinigamesRoute
  '/compare/$leftRsn/$rightRsn/quests': typeof CompareLeftRsnRightRsnQuestsRoute
  '/compare/$leftRsn/$rightRsn/skills': typeof CompareLeftRsnRightRsnSkillsRoute
  '/compare/$leftRsn/$rightRsn/xp-timeline': typeof CompareLeftRsnRightRsnXpTimelineRoute
  '/og/compare/$leftRsn/$rightRsn': typeof OgCompareLeftRsnRightRsnRoute
  '/compare/$leftRsn/$rightRsn': typeof CompareLeftRsnRightRsnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rating': typeof RatingRoute
  '/og/rating.png': typeof OgRatingDotpngRoute
  '/compare/$leftRsn/$rightRsn': typeof CompareLeftRsnRightRsnRouteWithChildren
  '/og/rating/$rsn': typeof OgRatingRsnRoute
  '/compare/$leftRsn/$rightRsn/achievement-diaries': typeof CompareLeftRsnRightRsnAchievementDiariesRoute
  '/compare/$leftRsn/$rightRsn/activity': typeof CompareLeftRsnRightRsnActivityRoute
  '/compare/$leftRsn/$rightRsn/bossing': typeof CompareLeftRsnRightRsnBossingRoute
  '/compare/$leftRsn/$rightRsn/clues': typeof CompareLeftRsnRightRsnCluesRoute
  '/compare/$leftRsn/$rightRsn/collections': typeof CompareLeftRsnRightRsnCollectionsRoute
  '/compare/$leftRsn/$rightRsn/combat-achievements': typeof CompareLeftRsnRightRsnCombatAchievementsRoute
  '/compare/$leftRsn/$rightRsn/efficiency': typeof CompareLeftRsnRightRsnEfficiencyRoute
  '/compare/$leftRsn/$rightRsn/minigames': typeof CompareLeftRsnRightRsnMinigamesRoute
  '/compare/$leftRsn/$rightRsn/quests': typeof CompareLeftRsnRightRsnQuestsRoute
  '/compare/$leftRsn/$rightRsn/skills': typeof CompareLeftRsnRightRsnSkillsRoute
  '/compare/$leftRsn/$rightRsn/xp-timeline': typeof CompareLeftRsnRightRsnXpTimelineRoute
  '/og/compare/$leftRsn/$rightRsn': typeof OgCompareLeftRsnRightRsnRoute
  '/compare/$leftRsn/$rightRsn/': typeof CompareLeftRsnRightRsnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/rating'
    | '/og/rating.png'
    | '/compare/$leftRsn/$rightRsn'
    | '/og/rating/$rsn'
    | '/compare/$leftRsn/$rightRsn/achievement-diaries'
    | '/compare/$leftRsn/$rightRsn/activity'
    | '/compare/$leftRsn/$rightRsn/bossing'
    | '/compare/$leftRsn/$rightRsn/clues'
    | '/compare/$leftRsn/$rightRsn/collections'
    | '/compare/$leftRsn/$rightRsn/combat-achievements'
    | '/compare/$leftRsn/$rightRsn/efficiency'
    | '/compare/$leftRsn/$rightRsn/minigames'
    | '/compare/$leftRsn/$rightRsn/quests'
    | '/compare/$leftRsn/$rightRsn/skills'
    | '/compare/$leftRsn/$rightRsn/xp-timeline'
    | '/og/compare/$leftRsn/$rightRsn'
    | '/compare/$leftRsn/$rightRsn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/rating'
    | '/og/rating.png'
    | '/og/rating/$rsn'
    | '/compare/$leftRsn/$rightRsn/achievement-diaries'
    | '/compare/$leftRsn/$rightRsn/activity'
    | '/compare/$leftRsn/$rightRsn/bossing'
    | '/compare/$leftRsn/$rightRsn/clues'
    | '/compare/$leftRsn/$rightRsn/collections'
    | '/compare/$leftRsn/$rightRsn/combat-achievements'
    | '/compare/$leftRsn/$rightRsn/efficiency'
    | '/compare/$leftRsn/$rightRsn/minigames'
    | '/compare/$leftRsn/$rightRsn/quests'
    | '/compare/$leftRsn/$rightRsn/skills'
    | '/compare/$leftRsn/$rightRsn/xp-timeline'
    | '/og/compare/$leftRsn/$rightRsn'
    | '/compare/$leftRsn/$rightRsn'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/rating'
    | '/og/rating.png'
    | '/compare/$leftRsn/$rightRsn'
    | '/og/rating/$rsn'
    | '/compare/$leftRsn/$rightRsn/achievement-diaries'
    | '/compare/$leftRsn/$rightRsn/activity'
    | '/compare/$leftRsn/$rightRsn/bossing'
    | '/compare/$leftRsn/$rightRsn/clues'
    | '/compare/$leftRsn/$rightRsn/collections'
    | '/compare/$leftRsn/$rightRsn/combat-achievements'
    | '/compare/$leftRsn/$rightRsn/efficiency'
    | '/compare/$leftRsn/$rightRsn/minigames'
    | '/compare/$leftRsn/$rightRsn/quests'
    | '/compare/$leftRsn/$rightRsn/skills'
    | '/compare/$leftRsn/$rightRsn/xp-timeline'
    | '/og/compare/$leftRsn/$rightRsn'
    | '/compare/$leftRsn/$rightRsn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RatingRoute: typeof RatingRoute
  OgRatingDotpngRoute: typeof OgRatingDotpngRoute
  CompareLeftRsnRightRsnRoute: typeof CompareLeftRsnRightRsnRouteWithChildren
  OgRatingRsnRoute: typeof OgRatingRsnRoute
  OgCompareLeftRsnRightRsnRoute: typeof OgCompareLeftRsnRightRsnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/rating.png': {
      id: '/og/rating.png'
      path: '/og/rating.png'
      fullPath: '/og/rating.png'
      preLoaderRoute: typeof OgRatingDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/rating/$rsn': {
      id: '/og/rating/$rsn'
      path: '/og/rating/$rsn'
      fullPath: '/og/rating/$rsn'
      preLoaderRoute: typeof OgRatingRsnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$leftRsn/$rightRsn': {
      id: '/compare/$leftRsn/$rightRsn'
      path: '/compare/$leftRsn/$rightRsn'
      fullPath: '/compare/$leftRsn/$rightRsn'
      preLoaderRoute: typeof CompareLeftRsnRightRsnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$leftRsn/$rightRsn/': {
      id: '/compare/$leftRsn/$rightRsn/'
      path: '/'
      fullPath: '/compare/$leftRsn/$rightRsn/'
      preLoaderRoute: typeof CompareLeftRsnRightRsnIndexRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/og/compare/$leftRsn/$rightRsn': {
      id: '/og/compare/$leftRsn/$rightRsn'
      path: '/og/compare/$leftRsn/$rightRsn'
      fullPath: '/og/compare/$leftRsn/$rightRsn'
      preLoaderRoute: typeof OgCompareLeftRsnRightRsnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$leftRsn/$rightRsn/xp-timeline': {
      id: '/compare/$leftRsn/$rightRsn/xp-timeline'
      path: '/xp-timeline'
      fullPath: '/compare/$leftRsn/$rightRsn/xp-timeline'
      preLoaderRoute: typeof CompareLeftRsnRightRsnXpTimelineRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/skills': {
      id: '/compare/$leftRsn/$rightRsn/skills'
      path: '/skills'
      fullPath: '/compare/$leftRsn/$rightRsn/skills'
      preLoaderRoute: typeof CompareLeftRsnRightRsnSkillsRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/quests': {
      id: '/compare/$leftRsn/$rightRsn/quests'
      path: '/quests'
      fullPath: '/compare/$leftRsn/$rightRsn/quests'
      preLoaderRoute: typeof CompareLeftRsnRightRsnQuestsRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/minigames': {
      id: '/compare/$leftRsn/$rightRsn/minigames'
      path: '/minigames'
      fullPath: '/compare/$leftRsn/$rightRsn/minigames'
      preLoaderRoute: typeof CompareLeftRsnRightRsnMinigamesRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/efficiency': {
      id: '/compare/$leftRsn/$rightRsn/efficiency'
      path: '/efficiency'
      fullPath: '/compare/$leftRsn/$rightRsn/efficiency'
      preLoaderRoute: typeof CompareLeftRsnRightRsnEfficiencyRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/combat-achievements': {
      id: '/compare/$leftRsn/$rightRsn/combat-achievements'
      path: '/combat-achievements'
      fullPath: '/compare/$leftRsn/$rightRsn/combat-achievements'
      preLoaderRoute: typeof CompareLeftRsnRightRsnCombatAchievementsRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/collections': {
      id: '/compare/$leftRsn/$rightRsn/collections'
      path: '/collections'
      fullPath: '/compare/$leftRsn/$rightRsn/collections'
      preLoaderRoute: typeof CompareLeftRsnRightRsnCollectionsRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/clues': {
      id: '/compare/$leftRsn/$rightRsn/clues'
      path: '/clues'
      fullPath: '/compare/$leftRsn/$rightRsn/clues'
      preLoaderRoute: typeof CompareLeftRsnRightRsnCluesRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/bossing': {
      id: '/compare/$leftRsn/$rightRsn/bossing'
      path: '/bossing'
      fullPath: '/compare/$leftRsn/$rightRsn/bossing'
      preLoaderRoute: typeof CompareLeftRsnRightRsnBossingRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/activity': {
      id: '/compare/$leftRsn/$rightRsn/activity'
      path: '/activity'
      fullPath: '/compare/$leftRsn/$rightRsn/activity'
      preLoaderRoute: typeof CompareLeftRsnRightRsnActivityRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
    '/compare/$leftRsn/$rightRsn/achievement-diaries': {
      id: '/compare/$leftRsn/$rightRsn/achievement-diaries'
      path: '/achievement-diaries'
      fullPath: '/compare/$leftRsn/$rightRsn/achievement-diaries'
      preLoaderRoute: typeof CompareLeftRsnRightRsnAchievementDiariesRouteImport
      parentRoute: typeof CompareLeftRsnRightRsnRoute
    }
  }
}

interface CompareLeftRsnRightRsnRouteChildren {
  CompareLeftRsnRightRsnAchievementDiariesRoute: typeof CompareLeftRsnRightRsnAchievementDiariesRoute
  CompareLeftRsnRightRsnActivityRoute: typeof CompareLeftRsnRightRsnActivityRoute
  CompareLeftRsnRightRsnBossingRoute: typeof CompareLeftRsnRightRsnBossingRoute
  CompareLeftRsnRightRsnCluesRoute: typeof CompareLeftRsnRightRsnCluesRoute
  CompareLeftRsnRightRsnCollectionsRoute: typeof CompareLeftRsnRightRsnCollectionsRoute
  CompareLeftRsnRightRsnCombatAchievementsRoute: typeof CompareLeftRsnRightRsnCombatAchievementsRoute
  CompareLeftRsnRightRsnEfficiencyRoute: typeof CompareLeftRsnRightRsnEfficiencyRoute
  CompareLeftRsnRightRsnMinigamesRoute: typeof CompareLeftRsnRightRsnMinigamesRoute
  CompareLeftRsnRightRsnQuestsRoute: typeof CompareLeftRsnRightRsnQuestsRoute
  CompareLeftRsnRightRsnSkillsRoute: typeof CompareLeftRsnRightRsnSkillsRoute
  CompareLeftRsnRightRsnXpTimelineRoute: typeof CompareLeftRsnRightRsnXpTimelineRoute
  CompareLeftRsnRightRsnIndexRoute: typeof CompareLeftRsnRightRsnIndexRoute
}

const CompareLeftRsnRightRsnRouteChildren: CompareLeftRsnRightRsnRouteChildren =
  {
    CompareLeftRsnRightRsnAchievementDiariesRoute:
      CompareLeftRsnRightRsnAchievementDiariesRoute,
    CompareLeftRsnRightRsnActivityRoute: CompareLeftRsnRightRsnActivityRoute,
    CompareLeftRsnRightRsnBossingRoute: CompareLeftRsnRightRsnBossingRoute,
    CompareLeftRsnRightRsnCluesRoute: CompareLeftRsnRightRsnCluesRoute,
    CompareLeftRsnRightRsnCollectionsRoute:
      CompareLeftRsnRightRsnCollectionsRoute,
    CompareLeftRsnRightRsnCombatAchievementsRoute:
      CompareLeftRsnRightRsnCombatAchievementsRoute,
    CompareLeftRsnRightRsnEfficiencyRoute:
      CompareLeftRsnRightRsnEfficiencyRoute,
    CompareLeftRsnRightRsnMinigamesRoute: CompareLeftRsnRightRsnMinigamesRoute,
    CompareLeftRsnRightRsnQuestsRoute: CompareLeftRsnRightRsnQuestsRoute,
    CompareLeftRsnRightRsnSkillsRoute: CompareLeftRsnRightRsnSkillsRoute,
    CompareLeftRsnRightRsnXpTimelineRoute:
      CompareLeftRsnRightRsnXpTimelineRoute,
    CompareLeftRsnRightRsnIndexRoute: CompareLeftRsnRightRsnIndexRoute,
  }

const CompareLeftRsnRightRsnRouteWithChildren =
  CompareLeftRsnRightRsnRoute._addFileChildren(
    CompareLeftRsnRightRsnRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  RatingRoute: RatingRoute,
  OgRatingDotpngRoute: OgRatingDotpngRoute,
  CompareLeftRsnRightRsnRoute: CompareLeftRsnRightRsnRouteWithChildren,
  OgRatingRsnRoute: OgRatingRsnRoute,
  OgCompareLeftRsnRightRsnRoute: OgCompareLeftRsnRightRsnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
