export const HISCORES_SKILL_NAMES = [
  "Overall",
  "Attack",
  "Defence",
  "Strength",
  "Hitpoints",
  "Ranged",
  "Prayer",
  "Magic",
  "Cooking",
  "Woodcutting",
  "Fletching",
  "Fishing",
  "Firemaking",
  "Crafting",
  "Smithing",
  "Mining",
  "Herblore",
  "Agility",
  "Thieving",
  "Slayer",
  "Farming",
  "Runecraft",
  "Hunter",
  "Construction",
  "Sailing",
] as const;

export const HISCORES_ACTIVITY_NAMES = [
  "Grid Points",
  "League Points",
  "Deadman Points",
  "Bounty Hunter - Hunter",
  "Bounty Hunter - Rogue",
  "Bounty Hunter (Legacy) - Hunter",
  "Bounty Hunter (Legacy) - Rogue",
  "Clue Scrolls (all)",
  "Clue Scrolls (beginner)",
  "Clue Scrolls (easy)",
  "Clue Scrolls (medium)",
  "Clue Scrolls (hard)",
  "Clue Scrolls (elite)",
  "Clue Scrolls (master)",
  "LMS - Rank",
  "PvP Arena - Rank",
  "Soul Wars Zeal",
  "Rifts closed",
  "Colosseum Glory",
  "Collections Logged",
  "Abyssal Sire",
  "Alchemical Hydra",
  "Amoxliatl",
  "Araxxor",
  "Artio",
  "Barrows Chests",
  "Brutus",
  "Bryophyta",
  "Callisto",
  "Calvar'ion",
  "Cerberus",
  "Chambers of Xeric",
  "Chambers of Xeric: Challenge Mode",
  "Chaos Elemental",
  "Chaos Fanatic",
  "Commander Zilyana",
  "Corporeal Beast",
  "Crazy Archaeologist",
  "Dagannoth Prime",
  "Dagannoth Rex",
  "Dagannoth Supreme",
  "Deranged Archaeologist",
  "Doom of Mokhaiotl",
  "Duke Sucellus",
  "General Graardor",
  "Giant Mole",
  "Grotesque Guardians",
  "Hespori",
  "Kalphite Queen",
  "King Black Dragon",
  "Kraken",
  "Kree'Arra",
  "K'ril Tsutsaroth",
  "Lunar Chests",
  "Mad Angel",
  "Maggot King",
  "Mimic",
  "Nex",
  "Nightmare",
  "Phosani's Nightmare",
  "Obor",
  "Phantom Muspah",
  "Sarachnis",
  "Scorpia",
  "Scurrius",
  "Shellbane Gryphon",
  "Skotizo",
  "Sol Heredit",
  "Spindel",
  "Tempoross",
  "The Gauntlet",
  "The Corrupted Gauntlet",
  "The Hueycoatl",
  "The Leviathan",
  "The Royal Titans",
  "The Whisperer",
  "Theatre of Blood",
  "Theatre of Blood: Hard Mode",
  "Thermonuclear Smoke Devil",
  "Tombs of Amascut",
  "Tombs of Amascut: Expert Mode",
  "TzKal-Zuk",
  "TzTok-Jad",
  "Vardorvis",
  "Venenatis",
  "Vet'ion",
  "Vorkath",
  "Wintertodt",
  "Yama",
  "Zalcano",
  "Zulrah",
] as const;

export function activityCategory(
  id: number,
  name: string,
): "activities" | "clues" | "bossing" | "minigames" {
  if (generalActivityNames.has(name)) return "activities";
  if (clueActivityNames.has(name)) return "clues";
  if (minigameActivityNames.has(name)) return "minigames";
  if (bossActivityNames.has(name)) return "bossing";
  if (id >= 20) return "bossing";
  return "activities";
}

export function isKnownHiscoresActivityName(name: string): boolean {
  return knownActivityNames.has(name);
}

const knownActivityNames = new Set<string>(HISCORES_ACTIVITY_NAMES);
const generalActivityNames = new Set<string>(
  HISCORES_ACTIVITY_NAMES.slice(0, 7),
);
const clueActivityNames = new Set<string>(HISCORES_ACTIVITY_NAMES.slice(7, 14));
const minigameActivityNames = new Set<string>(
  HISCORES_ACTIVITY_NAMES.slice(14, 20),
);
const bossActivityNames = new Set<string>(HISCORES_ACTIVITY_NAMES.slice(20));
